language: objective-c
os: osx
xcode_workspace: FastlaneProject.xcworkspace
xcode_scheme: FastlaneProject
xcode_sdk: iphonesimulator10.0
osx_image: xcode10.1
before_install:
- |
  brew update
  gem install xcpretty -N --no-ri --no-doc
  gem update fastlane
install: pod install
script:
- |
  set -o pipefail
  xcodebuild clean test -workspace FastlaneProject.xcworkspace -scheme talk7 -destination "platform=iOS Simulator,name=iPhone 6 Plus" | xcpretty

